openapi: 3.0.0
info:
  title: Product Service API
  version: 1.0.0
paths:
  /products:
    get:
      summary: Get list of products
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{productId}:
    get:
      summary: Get product by ID
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
components:
  schemas:
    Product:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        price: { type: number }
        count: { type: number }
        description: { type: string }
        image: { type: string }
